resolver: nightly-2018-11-06
packages:
- minlen
- mono-traversable
- mono-traversable-instances
- chunked-data
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- conduit-combinators
- mutable-containers
